# Generated by Django 5.0.6 on 2024-05-20 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pages', models.IntegerField()),
                ('format', models.TextField(choices=[('2', 'E-Book'), ('1', 'Fisico')], max_length=30)),
                ('edition', models.IntegerField()),
                ('releaseDate', models.DateField()),
                ('stats', models.CharField(choices=[('2', 'Cancelado'), ('1', 'Pendente'), ('3', 'Aprovado')], max_length=30)),
                ('stars', models.CharField(choices=[('4', '4'), ('2', '2'), ('1', '1'), ('3', '3'), ('5', '5')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowingDate', models.DateField(auto_now=True)),
                ('devolutionDate', models.DateField()),
                ('returnedDate', models.DateTimeField(blank=True, null=True)),
                ('bookFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookFKBorrowing', to='seraiva.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categoryFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookCategoryFK', to='seraiva.category'),
        ),
    ]
