# Generated by Django 5.0.6 on 2024-05-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('1', '1'), ('5', '5')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('1', 'Pendente'), ('3', 'Aprovado'), ('2', 'Cancelado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('3', 'admin'), ('2', 'author'), ('0', 'user'), ('1', 'librarian')], max_length=30),
        ),
    ]
