# Generated by Django 5.0.6 on 2024-05-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0002_alter_book_stars_alter_book_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('5', '5'), ('2', '2'), ('1', '1'), ('3', '3'), ('4', '4')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('2', 'Cancelado'), ('1', 'Pendente'), ('3', 'Aprovado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('2', 'author'), ('0', 'user'), ('3', 'admin'), ('1', 'librarian')], max_length=30),
        ),
    ]
