# Generated by Django 5.0.6 on 2024-06-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0003_alter_book_format_alter_book_stars_alter_book_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('5', '5'), ('2', '2'), ('4', '4'), ('3', '3'), ('1', '1')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('2', 'Cancelado'), ('1', 'Pendente'), ('3', 'Aprovado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('1', 'librarian'), ('0', 'user'), ('3', 'admin'), ('2', 'author')], max_length=30),
        ),
    ]
