# Generated by Django 5.0.6 on 2024-05-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0003_alter_book_format_alter_book_stars_alter_book_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.TextField(choices=[('1', 'Fisico'), ('2', 'E-Book')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('1', '1'), ('4', '4'), ('5', '5')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('2', 'Cancelado'), ('1', 'Pendente'), ('3', 'Aprovado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(choices=[('1', 'librarian'), ('3', 'admin'), ('0', 'user'), ('2', 'author')], max_length=30),
        ),
    ]
