# Generated by Django 5.0.6 on 2024-05-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0004_alter_book_stars_alter_book_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.TextField(choices=[('1', 'Fisico'), ('2', 'E-Book')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('1', '1'), ('5', '5'), ('2', '2'), ('4', '4'), ('3', '3')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('3', 'admin'), ('1', 'librarian'), ('2', 'author'), ('0', 'user')], max_length=30),
        ),
    ]
