# Generated by Django 5.0.6 on 2024-06-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0004_alter_book_stars_alter_book_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('1', '1'), ('2', '2'), ('4', '4')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('2', 'Cancelado'), ('3', 'Aprovado'), ('1', 'Pendente')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('2', 'author'), ('3', 'admin'), ('0', 'user'), ('1', 'librarian')], max_length=30),
        ),
    ]
