# Generated by Django 5.0.6 on 2024-05-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0005_alter_book_format_alter_book_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('4', '4'), ('1', '1'), ('2', '2'), ('5', '5'), ('3', '3')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('0', 'user'), ('3', 'admin'), ('1', 'librarian'), ('2', 'author')], max_length=30),
        ),
    ]
