# Generated by Django 5.0.6 on 2024-05-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0005_alter_book_format_alter_book_stars_alter_book_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.TextField(choices=[('1', 'Fisico'), ('2', 'E-Book')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('4', '4'), ('2', '2'), ('5', '5')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('2', 'Cancelado'), ('3', 'Aprovado'), ('1', 'Pendente')], max_length=30),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
