# Generated by Django 5.0.6 on 2024-05-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0006_alter_book_stars_alter_customuser_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('1', '1'), ('3', '3'), ('2', '2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('1', 'Pendente'), ('3', 'Aprovado'), ('2', 'Cancelado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('1', 'librarian'), ('0', 'user'), ('3', 'admin'), ('2', 'author')], max_length=30),
        ),
    ]
