# Generated by Django 5.0.6 on 2024-05-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0008_alter_book_format_alter_book_stars_alter_book_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('4', '4'), ('2', '2'), ('5', '5')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('3', 'Aprovado'), ('2', 'Cancelado'), ('1', 'Pendente')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('0', 'user'), ('3', 'admin'), ('1', 'librarian'), ('2', 'author')], max_length=30),
        ),
    ]
