# Generated by Django 5.0.6 on 2024-05-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0009_alter_book_stars_alter_book_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('2', 'Cancelado'), ('3', 'Aprovado'), ('1', 'Pendente')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('1', 'librarian'), ('3', 'admin'), ('0', 'user'), ('2', 'author')], max_length=30),
        ),
    ]
