# Generated by Django 5.0.6 on 2024-05-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0010_alter_book_stars_alter_book_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.TextField(choices=[('1', 'Fisico'), ('2', 'E-Book')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('1', '1'), ('3', '3'), ('2', '2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('1', 'Pendente'), ('2', 'Cancelado'), ('3', 'Aprovado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('0', 'user'), ('2', 'author'), ('3', 'admin'), ('1', 'librarian')], max_length=30),
        ),
    ]
