# Generated by Django 5.0.6 on 2024-05-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0011_alter_book_format_alter_book_stars_alter_book_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('3', '3'), ('1', '1')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('3', 'Aprovado'), ('1', 'Pendente'), ('2', 'Cancelado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('1', 'librarian'), ('0', 'user'), ('2', 'author'), ('3', 'admin')], max_length=30),
        ),
    ]
