# Generated by Django 5.0.6 on 2024-05-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seraiva', '0012_alter_book_description_alter_book_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('5', '5'), ('1', '1'), ('3', '3'), ('2', '2'), ('4', '4')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.CharField(choices=[('3', 'Aprovado'), ('2', 'Cancelado'), ('1', 'Pendente')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('3', 'admin'), ('2', 'author'), ('0', 'user'), ('1', 'librarian')], max_length=30),
        ),
    ]
